# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160411_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 1, 10, 35, 567446)),
        ),
    ]
