# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160411_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 1, 32, 20, 706015)),
        ),
    ]
